config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :medics
  resources :patients do
    resources :appointments
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  # Fields should be free of needless validations. There are no strict rules about naming cities, streets, etc.
  belongs_to :patient
  validates :cep, presence: true, length: { is: 8 }, uniqueness: true, numericality: { only_integer: true, message: "should only contain numbers" }
  validates :city, presence: true
  validates :zone, presence: true
  validates :street, presence: true
  validates :complement, presence: true
  validates :patient, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :medic
  belongs_to :patient
  validates :date, presence: true, comparison: {greater_than: Time.now}
  validates :time, presence: true
  validates :medic_id, presence: true
  validates :patient_id, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/medic.rb
class Medic < ApplicationRecord
  has_many :appointments

  validates :name, presence: true
  validates :cpf, presence: true, length: { is: 11 }, uniqueness: true, numericality: { only_integer: true, message: "should only contain numbers" }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :crm, presence:true, uniqueness: true, numericality: { only_integer: true }
  validates :speciality, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_one :address, dependent: :destroy
  has_many :appointments, dependent: :destroy
  accepts_nested_attributes_for :address

  validates :name, presence: true
  validates :birth, presence: true, comparison: {less_than: Time.now}
  validates :cpf, presence: true, length: { is: 11 }, uniqueness: true, numericality: { only_integer: true, message: "should only contain numbers" }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def create
    @patient = Patient.find(params[:patient_id])
    @appointment = @patient.appointments.create(appointment_params)
    redirect_to patient_path(@patient)
  end
end

def destroy
  @patient = Patient.find(params[:patient_id])
  @appointment = @patient.appointments.find(params[:id])
  @appointment.destroy
  redirect_to patient_path(@patient), status: :see_other
end

private
def appointment_params
  params.require(:appointment).permit(:date, :time, :medic_id)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController

  def index
    @medic = Medic.all
  end

  def new
    @medic = Medic.new
  end

  def create
    @medic = Medic.new(medic_params)
    if @medic.save
      redirect_to @medic
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @medic = Medic.find(params[:id])
  end

  def update
    @medic = Medic.find(params[:id])
    if @medic.update(medic_params)
      redirect_to @medic
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @medic = Medic.find(params[:id])
  end

  def destroy
    @medic = Medic.find(params[:id])
    @medic.destroy

    redirect_to root_path, status: :see_other
  end
end

private
def medic_params
  params.require(:medic).permit(:name, :cpf, :email, :crm, :speciality)
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patient = Patient.all
  end

  def new
    @patient = Patient.new
    @patient.build_address
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to root_path, status: :see_other
  end
end

private
def patient_params
  params.require(:patient).permit(:name, :birth, :cpf, :email, address_attributes: [:id, :cep, :city, :zone, :street, :complement])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_appointment.html.erb
<table border="2" align="center" bgcolor=#5f9ea0>
  <tr>
    <td>
      Hora da consulta:
    </td>
    <td>
      <%= appointment.time.to_formatted_s(:time) %>
    </td>
  </tr>
  <tr>
    <td>
      Data da consulta:
    </td>
    <td>
      <%= appointment.date.strftime('%d/%m/%Y') %>
    </td>
  </tr>
  <tr>
    <td>
      Medico:
    </td>
    <td>
      <%= appointment.medic.name %>
    </td>
  </tr>
  <tr>
    <td>
      Paciente:
    </td>
    <td>
      <%= appointment.patient.name %>
    </td>
  </tr>
</table>

app/views/appointments/_form.html.erb
<%= form_with model: [ @patient, @patient.appointments.build ] do |form| %>
  <p>
    <%= form.label :Data %><br>
    <%= form.date_field :date %>
  </p>
  <p>
    <%= form.label :Hora %><br>
    <%= form.time_field :time %>
  </p>
  <p>
    <%= form.label :Medico %><br>
    <%= form.select :medic_id , options_for_select(Medic.all.pluck(:name, :id))%>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<table border="2" align="center" bgcolor="#228b22">
  <tr>
    <td>
      <table>
        <tr>
          <td>
            Paciente
          </td>
          <td>
            <%= image_tag 'man_with_cane.gif' %>
          </td>
        </tr>
      </table>
    </td>
    <td>
      <table>
        <tr>
          <td>
            Medico
          </td>
          <td>
            <%= image_tag 'doctor.gif' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "Criar", new_patient_path %>
    </td>
    <td class="medic">
      <%= link_to "Criar", new_medic_path %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "Listar Todos", patients_url %>
    </td>
    <td>
      <%= link_to "Listar Todos", medics_path %>
    </td>
  </tr>
  <tr>
    <td colspan="2">
      <div align="center">
        <%= image_tag 'medicine.gif' %>
      </div>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/medics/_form.html.erb
<%= form_with model: @medic do |form| %>
  <% if @medic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medic.errors.count, "error") %> ocorreram durante o cadastro:</h2>
      <ul>
        <% @medic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table border="2" align="center" bgcolor="#6495ed">
    <tr>
      <td>
        <%= form.label :name %>
      </td>
      <td>
        <%= form.text_field :name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label "CPF (apenas números)" %>
      </td>
      <td>
        <%= form.text_field :cpf %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :email %>
      </td>
      <td>
        <%= form.email_field :email %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :speciality %>
      </td>
      <td>
        <%= form.text_field :speciality %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :crm %>
      </td>
      <td>
        <%= form.text_field :crm %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <div align="center">
          <%= form.submit %>
        </div>
      </td>
    </tr>
  </table>
<% end %>

app/views/medics/edit.html.erb
<table border="1" align="center" bgcolor="#daa520">
  <tr>
    <td>
      <div align="center">
        <h3>Editar Médico</h3>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <%= render "form", medic: @medic %>
    </td>
  </tr>
</table>

app/views/medics/index.html.erb
<table border="2" align="center" bgcolor="#228b22">
  <tr>
    <td colspan="2">
      <table>
        <tr>
          <td>
            Medicos
          </td>
          <td>
            <%= image_tag 'doctor.gif' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <% @medic.each do |medic| %>
    <tr>
      <td>
        <%= link_to medic.name, medic %>
      </td>
    </tr>
  <% end %>
</table>

app/views/medics/new.html.erb
<table border="1" align="center" bgcolor="#daa520">
  <tr>
    <td>
      <div align="center">
        <h3>Cadastro do Médico</h3>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <%= render "form", medic: @medic %>
    </td>
  </tr>
</table>

app/views/medics/show.html.erb
<table border="1" bgcolor=#daa520 align="center">
  <tr>
    <td>
      <table border="2" align="center" bgcolor=#5f9ea0>
        <tr>
          <td colspan="2">
            <div align="center">
              Dados do Medico
            </div>
          </td>
        </tr>
        <tr>
          <td>
            Nome:
          </td>
          <td>
            <%= @medic.name %>
          </td>
        </tr>
        <tr>
          <td>
            CPF:
          </td>
          <td>
            <%= @medic.cpf %>
          </td>
        </tr>
        <tr>
          <td>
            E-mail:
          </td>
          <td>
            <%= @medic.email %>
          </td>
        </tr>
        <tr>
          <td>
            Especialidade:
          </td>
          <td>
            <%= @medic.speciality %>
          </td>
        </tr>
        <tr>
          <td>
            CRM:
          </td>
          <td>
            <%= @medic.crm %>
          </td>
        </tr>
      </table>

      <br>

      <table border="2" align="center" bgcolor=#5f9ea0>
        <tr>
          <td colspan="2">
            <div align="center">
              Consultas
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <%= render @medic.appointments %>
          </td>
        </tr>
        <tr>
      </table>
    </td>
  </tr>
</table>
<br>

<table border="2" align="center" bgcolor="#228b22">
  <tr>
    <td>
      <table>
        <tr>
          <td>
            <%= link_to "Editar", edit_medic_path(@medic) %>
          </td>
          <td>
            <%= image_tag 'notebook.gif' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <table>
        <tr>
          <td>
            <%= link_to "Deletar", medic_path(@medic), data: {
              turbo_method: :delete,
              turbo_confirm: "Tem certeza?"
            } %>
          </td>
          <td>
            <%= image_tag 'RedX.gif' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

app/views/patients/_form.html.erb
<%= form_with model: patient do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> ocorreram durante o cadastro:</h2>
      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table border="1" align="center" bgcolor="#6495ed">
    <tr>
      <td>
        <table border="2" align="center" bgcolor="#6495ed">
          <tr>
            <td>
              <%= form.label :nome %>
            </td>
            <td>
              <%= form.text_field :name %>
            </td>
          </tr>

          <tr>
            <td>
              <%= form.label :"data de nascimento" %>
            </td>
            <td>
              <%= form.date_field :birth %>
            </td>
          </tr>

          <tr>
            <td>
              <%= form.label "CPF (apenas números)" %>
            </td>
            <td>
              <%= form.text_field :cpf %>
            </td>
          </tr>

          <tr>
            <td>
              <%= form.label :email %>
            </td>
            <td>
              <%= form.email_field :email %>
            </td>
          </tr>
        </table>
      </td>
      <td>
        <table border="2" align="center" bgcolor="#6495ed">
          <tr>
            <%= form.fields_for :address do |address_form| %>
              <td>
                <%= address_form.label "CEP (apenas números)" %>
              </td>
              <td>
                <%= address_form.text_field :cep %>
              </td>
              </tr>
              <tr>
                <td>
                  <%= address_form.label :cidade %>
                </td>
                <td>
                  <%= address_form.text_field :city %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= address_form.label :bairro %>
                </td>
                <td>
                  <%= address_form.text_field :zone %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= address_form.label :logradouro %>
                </td>
                <td>
                  <%= address_form.text_field :street %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= address_form.label :complemento %>
                </td>
                <td>
                  <%= address_form.text_field :complement %>
                </td>
              </tr>
              </table>
            <% end %>
    <tr>
      <td colspan="2">
        <div align="center">
          <%= form.submit %>
        </div>
      </td>
    </tr>
    </td>
    </tr>
  </table>
<% end %>

app/views/patients/edit.html.erb
<table border="1" align="center" bgcolor="#daa520">
  <tr>
    <td>
      <div align="center">
        <h3>Editar Paciente</h3>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <%= render "form", patient: @patient %>
    </td>
  </tr>
</table>

app/views/patients/index.html.erb
<table border="2" align="center" bgcolor="#228b22">
  <tr>
    <td colspan="2">
      <table>
        <tr>
          <td>
            Pacientes
          </td>
          <td>
            <%= image_tag 'man_with_cane.gif' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <% @patient.each do |patient| %>
    <tr>
      <td>
        <%= link_to patient.name, patient %>
      </td>
    </tr>
  <% end %>
</table>

app/views/patients/new.html.erb
<table border="1" align="center" bgcolor="#daa520">
  <tr>
    <td>
      <div align="center">
        <h3>Cadastro do Paciente</h3>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <%= render "form", patient: @patient %>
    </td>
  </tr>
</table>

app/views/patients/show.html.erb
<table border="1" bgcolor=#daa520 align="center">
  <tr>
    <td>
      <table border="2" align="center" bgcolor=#5f9ea0>
        <tr>
          <td colspan="2">
            <div align="center">
              Dados do Paciente
            </div>
          </td>
        </tr>
        <tr>
          <td>
            Nome:
          </td>
          <td>
            <%= @patient.name %>
          </td>
        </tr>
        <tr>
          <td>
            CPF:
          </td>
          <td>
            <%= @patient.cpf %>
          </td>
        </tr>
        <tr>
          <td>
            E-mail:
          </td>
          <td>
            <%= @patient.email %>
          </td>
        </tr>
        <tr>
          <td>
            Data de Nascimento:
          </td>
          <td>
            <%= @patient.birth %>
          </td>
        </tr>
      </table>

      <br>

      <table border="2" align="center" bgcolor=#5f9ea0>
        <tr>
          <td colspan="2">
            <div align="center">
              Endereço do Paciente
            </div>
          </td>
        </tr>
        <tr>
          <td>
            Cidade:
          </td>
          <td>
            <%= @patient.address.city %>
          </td>
        </tr>
        <tr>
          <td>
            Logradouro:
          </td>
          <td>
            <%= @patient.address.street %>
          </td>
        </tr>
        <tr>
          <td>
            Bairro:
          </td>
          <td>
            <%= @patient.address.zone %>
          </td>
        </tr>
        <tr>
          <td>
            CEP:
          </td>
          <td>
            <%= @patient.address.cep %>
          </td>
        </tr>
        <tr>
          <td>
            Complemento:
          </td>
          <td>
            <%= @patient.address.complement %>
          </td>
        </tr>
      </table>
    </td>

    <br>

    <td>
      <table border="2" align="center" bgcolor=#5f9ea0>
        <tr>
          <td colspan="2">
            <div align="center">
              Consultas
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <%= render @patient.appointments %>
          </td>
        </tr>
        <tr>
      </table>

      <br>

      <table border="2" align="center" bgcolor="#6495ed">
        <tr>
          <td colspan="2">
            <div align="center">
              Nova Consulta:
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <%= render 'appointments/form'%>
          </td>
        </tr>
        <tr>
      </table>
    </td>
  </tr>
</table>
<br>
<table border="2" align="center" bgcolor="#228b22">
  <tr>
    <td>
      <table>
        <tr>
          <td>
            <%= link_to "Editar", edit_patient_path(@patient) %>
          </td>
          <td>
            <%= image_tag 'notebook.gif' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <table>
        <tr>
          <td>
            <%= link_to "Deletar", patient_path(@patient), data: {
              turbo_method: :delete,
              turbo_confirm: "Tem certeza?"
            } %>
          </td>
          <td>
            <%= image_tag 'RedX.gif' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>